/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.7.0] */
/* PROTOCOL [CAN] */
/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */
/* Start BUSMASTER global variable */
/* End BUSMASTER global variable */
/* Start BUSMASTER Function Prototype */
GCC_EXTERN void GCC_EXPORT OnMsg_All(STCAN_MSG RxMsg);
GCC_EXTERN void GCC_EXPORT OnKey_d(unsigned char KeyValue);
GCC_EXTERN void GCC_EXPORT OnError_Warning_Limit(SCAN_ERR ErrorMsg);
GCC_EXTERN void GCC_EXPORT OnDLL_Load();
GCC_EXTERN void GCC_EXPORT OnDLL_Unload();
GCC_EXTERN void GCC_EXPORT OnTimer_new_100( );
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
GCC_EXTERN void GCC_EXPORT OnBus_Disconnect();
/* End BUSMASTER Function Prototype */
/* Start BUSMASTER generated function - OnMsg_All */
void OnMsg_All(STCAN_MSG RxMsg)
{
// Initialise message structure
RxMsg.m_unMsgID = 0x100; // Message ID
RxMsg.m_ucEXTENDED = FALSE; // Standard Message type
RxMsg.m_ucRTR = FALSE; // Not RTR type
RxMsg.m_ucDLC = 8; // Length is 8 Bytes
RxMsg.m_sWhichBit.m_aulData[0] = 10; // Lower 4 Bytes
RxMsg.m_sWhichBit.m_aulData[1] = 20; // Upper 4 Bytes
RxMsg.m_ucChannel = 1;
SendMsg(RxMsg);
}/* End BUSMASTER generated function - OnMsg_All */
/* Start BUSMASTER generated function - OnKey_d */
void OnKey_d(unsigned char KeyValue)
{
Connect();
}/* End BUSMASTER generated function - OnKey_d */
/* Start BUSMASTER generated function - OnError_Warning_Limit */
void OnError_Warning_Limit(SCAN_ERR ErrorMsg)
{
Trace("Warning Limit reached");
}/* End BUSMASTER generated function - OnError_Warning_Limit */
/* Start BUSMASTER generated function - OnDLL_Load */
void OnDLL_Load()
{
/* TODO: Define and Initialise the following variables*/
EnableLogging();
}/* End BUSMASTER generated function - OnDLL_Load */
/* Start BUSMASTER generated function - OnDLL_Unload */
void OnDLL_Unload()
{
/* TODO: Define and Initialise the following variables*/
DisableLogging();
}/* End BUSMASTER generated function - OnDLL_Unload */
/* Start BUSMASTER generated function - OnTimer_new_100 */
void OnTimer_new_100( )
{
// Initialise message structure
STCAN_MSG sMsg;
sMsg.m_unMsgID = 0x20; // Message ID
sMsg.m_ucEXTENDED = FALSE; // Standard Message type
sMsg.m_ucRTR = FALSE; // Not RTR type
sMsg.m_ucDLC = 8; // Length is 8 Bytes
sMsg.m_sWhichBit.m_aulData[0] = 10; // Lower 4 Bytes
sMsg.m_sWhichBit.m_aulData[1] = 20; // Upper 4 Bytes
sMsg.m_sWhichBit.m_aulData[2] = 30; // Upper 4 Bytes
sMsg.m_ucChannel = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - OnTimer_new_100 */
/* Start BUSMASTER generated function - OnBus_Connect */
void OnBus_Connect()
{
Trace("Bus connected");
}/* End BUSMASTER generated function - OnBus_Connect */
/* Start BUSMASTER generated function - OnBus_Disconnect */
void OnBus_Disconnect()
{
Trace("Bus Disconnected");
}/* End BUSMASTER generated function - OnBus_Disconnect */